version: 2
updates:
  - package-ecosystem: maven
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris
    labels:
      - area/dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: daily
      time: "19:30"
      timezone: Europe/Paris